// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("pat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pat"] = "";
        }
        if (!("org" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["org"] = "";
        }
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["project"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class Ticket {
    /**
     * Creates a new Ticket instance.
     * @param {Partial<Ticket>} [$$source = {}] - The source object to create the Ticket.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["State"] = "";
        }
        if (!("PRLinks" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["PRLinks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ticket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Ticket}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PRLinks" in $$parsedSource) {
            $$parsedSource["PRLinks"] = $$createField4_0($$parsedSource["PRLinks"]);
        }
        return new Ticket(/** @type {Partial<Ticket>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
