// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckAppState() {
    return $Call.ByID(3733172107);
}

/**
 * @returns {$CancellablePromise<models$0.Ticket[]>}
 */
export function FetchAssignedTickets() {
    return $Call.ByID(1514196524).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Ticket[]>}
 */
export function FetchAssignedTicketsCache() {
    return $Call.ByID(2655116166).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {config$0.AzureCFG} cfg
 * @returns {$CancellablePromise<models$0.Ticket[]>}
 */
export function InitializeApp(cfg) {
    return $Call.ByID(1653907426, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2140409555);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartPolling() {
    return $Call.ByID(1840371022);
}

// Private type creation functions
const $$createType0 = models$0.Ticket.createFrom;
const $$createType1 = $Create.Array($$createType0);
