// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as azuredevops$0 from "../../azuredevops/models.js";

/**
 * @returns {$CancellablePromise<azuredevops$0.Ticket[]>}
 */
export function FetchAssignedTickets() {
    return $Call.ByID(1514196524).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<azuredevops$0.Ticket[]>}
 */
export function FetchAssignedTicketsCache() {
    return $Call.ByID(2655116166).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2140409555);
}

/**
 * @param {azuredevops$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function StoreConfig(cfg) {
    return $Call.ByID(1270630292, cfg);
}

/**
 * @param {azuredevops$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function ValidateConfig(cfg) {
    return $Call.ByID(4044659485, cfg);
}

// Private type creation functions
const $$createType0 = azuredevops$0.Ticket.createFrom;
const $$createType1 = $Create.Array($$createType0);
