// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../../../github.com/wailsapp/wails/v3/pkg/services/notifications/models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckNotificationAuthorization() {
    return $Call.ByID(2737426684);
}

/**
 * @param {notifications$0.NotificationCategory} category
 * @returns {$CancellablePromise<void>}
 */
export function RegisterNotificationCategory(category) {
    return $Call.ByID(1154743454, category);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAllDeliveredNotifications() {
    return $Call.ByID(3562598511);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAllPendingNotifications() {
    return $Call.ByID(2370461114);
}

/**
 * @param {string} identifier
 * @returns {$CancellablePromise<void>}
 */
export function RemoveDeliveredNotification(identifier) {
    return $Call.ByID(1205685723, identifier);
}

/**
 * @param {string} identifier
 * @returns {$CancellablePromise<void>}
 */
export function RemoveNotification(identifier) {
    return $Call.ByID(3633039715, identifier);
}

/**
 * @param {string} categoryID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveNotificationCategory(categoryID) {
    return $Call.ByID(2411946599, categoryID);
}

/**
 * @param {string} identifier
 * @returns {$CancellablePromise<void>}
 */
export function RemovePendingNotification(identifier) {
    return $Call.ByID(901200792, identifier);
}

/**
 * Public methods that delegate to the implementation.
 * @returns {$CancellablePromise<boolean>}
 */
export function RequestNotificationAuthorization() {
    return $Call.ByID(1855753079);
}

/**
 * @param {notifications$0.NotificationOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function SendNotification(options) {
    return $Call.ByID(3467925233, options);
}

/**
 * @param {notifications$0.NotificationOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function SendNotificationWithActions(options) {
    return $Call.ByID(3859329828, options);
}

/**
 * @param {string} id
 * @param {string} title
 * @param {string} body
 * @param {string} subtitle
 * @returns {$CancellablePromise<void>}
 */
export function SystemNotification(id, title, body, subtitle) {
    return $Call.ByID(3315121798, id, title, body, subtitle);
}
