// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Ticket {
    /**
     * Creates a new Ticket instance.
     * @param {Partial<Ticket>} [$$source = {}] - The source object to create the Ticket.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("State" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["State"] = "";
        }
        if (!("Tags" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Tags"] = "";
        }
        if (!("AssignedTo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AssignedTo"] = "";
        }
        if (!("IsAssignedToMe" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsAssignedToMe"] = false;
        }
        if (!("ChangedDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ChangedDate"] = "";
        }
        if (!("LastNotifiedDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LastNotifiedDate"] = "";
        }
        if (!("PRIds" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["PRIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ticket instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Ticket}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PRIds" in $$parsedSource) {
            $$parsedSource["PRIds"] = $$createField9_0($$parsedSource["PRIds"]);
        }
        return new Ticket(/** @type {Partial<Ticket>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
