// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AzureCFG {
    /**
     * Creates a new AzureCFG instance.
     * @param {Partial<AzureCFG>} [$$source = {}] - The source object to create the AzureCFG.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("pat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pat"] = "";
        }
        if (!("org" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["org"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["project"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["validate"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AzureCFG instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AzureCFG}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AzureCFG(/** @type {Partial<AzureCFG>} */($$parsedSource));
    }
}
